services:
  mysql:
    image: mysql:8.0
    container_name: climate_mysql_container
    environment:
      #MYSQL_ROOT_PASSWORD: rootpassword
      - MYSQL_DATABASE=climate_db
      #- MYSQL_USER=user
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3306:3306"
    volumes:
      - climate_mysql_data:/var/lib/mysql
volumes:
  climate_mysql_data: